function adjustWaypoints() {
  const waypoints = [
    {
      x: 205,
      y: 136,
    },
    {
      x: 282,
      y: 180,
    },
    {
      x: 285,
      y: 920,
    },
    {
      x: 536,
      y: 918,
    },
    {
      x: 542,
      y: 796,
    },
    {
      x: 792,
      y: 794,
    },
    {
      x: 792,
      y: 478,
    },
    {
      x: 730,
      y: 472,
    },
    {
      x: 732,
      y: 288,
    },
    {
      x: 1430,
      y: 286,
    },
    {
      x: 1432,
      y: 474,
    },
    {
      x: 924,
      y: 478,
    },
    {
      x: 924,
      y: 792,
    },
    {
      x: 1248,
      y: 794,
    },
    {
      x: 1310,
      y: 906,
    },
    {
      x: 1456,
      y: 880,
    },
  ];
  const newWaypoints = [];
  waypoints.forEach((wp) => {
    newWaypoints.push({
      x: wp.x / 1.6,
      y: wp.y / 1.6,
    });
  });
  return newWaypoints;
}

const enemyTypes = {
  torch: {
    height: 30,
    width: 70,
    health: 80,
    color: "red",
    speed: 2,
    coins: 100,
    enemySrc: "../../assets/enemies/torch.png",
    frames: { max: 13 },
  },
  tnt: {
    height: 40,
    width: 40,
    health: 30,
    color: "green",
    speed: 5,
    coins: 75,
    enemySrc: "../../assets/enemies/tnt.png",
    frames: { max: 12 },
  },
};

const buildingTypes = {
  tower01: [
    {
      rate: 40,
      range: 120,
      damage: 1900,
      src: "./assets/towers/Tower 01.png",
      frames: {
        max: 3,
        current: 0,
      },
      weaponSrc: "./assets/weapons/Tower 01 - Level 01 - Weapon.png",
      weaponFrames: { max: 6 },
      bulletSrc: "./assets/bullets/Tower 01 - Level 01 - Projectile.png",
      bulletFrames: { max: 3 },
      bulletProps: {
        x: 6,
        y: 34,
        translate: 31,
      },
      size: {
        dw: 40,
        dh: 85,
        dy: 45,
      },
      weaponProps: {
        size: 90,
        translate: -13,
      },
      areaDamage: false,
      levelupcost: 8000,
      weaponRotate: true,
    },
    {
      rate: 36,
      range: 130,
      damage: 1900 * 2,
      src: "./assets/towers/Tower 01.png",
      frames: { max: 3, current: 1 },
      weaponSrc: "./assets/weapons/Tower 01 - Level 02 - Weapon.png",
      weaponFrames: { max: 6 },
      bulletSrc: "./assets/bullets/Tower 01 - Level 02 - Projectile.png",
      bulletFrames: { max: 3 },
      bulletProps: {
        x: 12,
        y: 34,
        translate: 33,
      },
      size: {
        dw: 40,
        dh: 85,
        dy: 45,
      },
      weaponProps: {
        size: 90,
        translate: -16,
      },
      areaDamage: false,
      levelupcost: 8000 * 2,
      weaponRotate: true,
    },
    {
      rate: 32,
      range: 140,
      damage: 1900 * 4,
      src: "./assets/towers/Tower 01.png",
      frames: { max: 3, current: 2 },
      weaponSrc: "./assets/weapons/Tower 01 - Level 03 - Weapon.png",
      weaponFrames: { max: 6 },
      bulletSrc: "./assets/bullets/Tower 01 - Level 03 - Projectile.png",
      bulletFrames: { max: 3 },
      bulletProps: {
        x: 18,
        y: 34,
        translate: 34,
      },
      size: {
        dw: 40,
        dh: 85,
        dy: 45,
      },
      weaponProps: {
        size: 85,
        translate: -20,
      },
      areaDamage: false,
      levelupcost: 8000 * 4,
      weaponRotate: true,
    },
    {
      rate: 28,
      range: 150,
      damage: 1900 * 8,
      src: "./assets/towers/Tower 06.png",
      frames: { max: 3, current: 0 },
      weaponSrc: "./assets/weapons/Tower 06 - Level 01 - Weapon.png",
      weaponFrames: { max: 6 },
      bulletSrc: "./assets/bullets/Tower 06 - Level 01 - Projectile.png",
      bulletFrames: { max: 3 },
      bulletProps: {
        x: 6,
        y: 34,
        translate: 31,
      },
      size: {
        dw: 40,
        dh: 85,
        dy: 45,
      },
      weaponProps: {
        size: 70,
        translate: -13,
      },
      areaDamage: false,
      levelupcost: 8000 * 8,
      weaponRotate: true,
    },
    {
      rate: 24,
      range: 160,
      damage: 1900 * 16,
      src: "./assets/towers/Tower 06.png",
      frames: { max: 3, current: 1 },
      weaponSrc: "./assets/weapons/Tower 06 - Level 02 - Weapon.png",
      weaponFrames: { max: 6 },
      bulletSrc: "./assets/bullets/Tower 06 - Level 02 - Projectile.png",
      bulletFrames: { max: 4 },
      bulletProps: {
        x: 12,
        y: 34,
        translate: 32,
      },
      size: {
        dw: 40,
        dh: 85,
        dy: 45,
      },
      weaponProps: {
        size: 90,
        translate: -16,
      },
      areaDamage: false,
      levelupcost: 8000 * 16,
      weaponRotate: true,
    },
    {
      rate: 20,
      range: 170,
      damage: 1900 * 32,
      src: "./assets/towers/Tower 06.png",
      frames: { max: 3, current: 2 },
      weaponSrc: "./assets/weapons/Tower 06 - Level 03 - Weapon.png",
      weaponFrames: { max: 6 },
      bulletSrc: "./assets/bullets/Tower 06 - Level 03 - Projectile.png",
      bulletFrames: { max: 4 },
      bulletProps: {
        x: 15,
        y: 34,
        translate: 32,
      },
      size: {
        dw: 40,
        dh: 85,
        dy: 45,
      },
      weaponProps: {
        size: 90,
        translate: -16,
      },
      areaDamage: false,
      levelupcost: " max",
      weaponRotate: true,
    },
  ],
  tower02: [
    {
      rate: 40,
      range: 120,
      damage: 5,
      src: "./assets/towers/Tower 02.png",
      frames: { max: 3, current: 0 },
      weaponSrc: "./assets/weapons/Tower 02 - Level 01 - Weapon.png",
      weaponFrames: { max: 26 },
      bulletSrc: "./assets/bullets/Tower 02 - Level 01 - Projectile.png",
      bulletFrames: { max: 5 },
      bulletProps: {
        x: 6,
        y: 34,
        translate: 32,
      },
      size: {
        dw: 40,
        dh: 120,
        dy: 80,
      },
      weaponProps: {
        size: 40,
        translate: -13,
      },
      areaDamage: true,
      levelupcost: 20000000,
      weaponRotate: false,
    },
    {
      rate: 26,
      range: 140,
      damage: 250,
      src: "./assets/towers/Tower 02.png",
      frames: { max: 3, current: 0 },
      weaponSrc: "./assets/weapons/Tower 02 - Level 01 - Weapon.png",
      weaponFrames: { max: 26 },
      bulletSrc: "./assets/bullets/Tower 02 - Level 01 - Projectile.png",
      bulletFrames: { max: 5 },
      bulletProps: {
        x: 6,
        y: 34,
        translate: 32,
      },
      size: {
        dw: 40,
        dh: 120,
        dy: 80,
      },
      weaponProps: {
        size: 40,
        translate: -13,
      },
      areaDamage: true,
      levelupcost: 20000000 * 10,
      weaponRotate: false,
    },
    {
      rate: 22,
      range: 160,
      damage: 2500,
      src: "./assets/towers/Tower 02.png",
      frames: { max: 3, current: 1 },
      weaponSrc: "./assets/weapons/Tower 02 - Level 02 - Weapon.png",
      weaponFrames: { max: 33 },
      bulletSrc: "./assets/bullets/Tower 02 - Level 01 - Projectile.png",
      bulletFrames: { max: 5 },
      bulletProps: {
        x: 6,
        y: 34,
        translate: 32,
      },
      size: {
        dw: 40,
        dh: 120,
        dy: 80,
      },
      weaponProps: {
        size: 40,
        translate: -18,
      },
      areaDamage: true,
      levelupcost: 20000000 * 40,
      weaponRotate: false,
    },
    {
      rate: 20,
      range: 180,
      damage: 8000,
      src: "./assets/towers/Tower 02.png",
      frames: { max: 3, current: 1 },
      weaponSrc: "./assets/weapons/Tower 02 - Level 02 - Weapon.png",
      weaponFrames: { max: 33 },
      bulletSrc: "./assets/bullets/Tower 02 - Level 01 - Projectile.png",
      bulletFrames: { max: 5 },
      bulletProps: {
        x: 6,
        y: 34,
        translate: 32,
      },
      size: {
        dw: 40,
        dh: 120,
        dy: 80,
      },
      weaponProps: {
        size: 40,
        translate: -18,
      },
      areaDamage: true,
      levelupcost: 20000000 * 70,
      weaponRotate: false,
    },
    {
      rate: 18,
      range: 200,
      damage: 20000,
      src: "./assets/towers/Tower 02.png",
      frames: { max: 3, current: 2 },
      weaponSrc: "./assets/weapons/Tower 02 - Level 03 - Weapon.png",
      weaponFrames: { max: 39 },
      bulletSrc: "./assets/bullets/Tower 02 - Level 01 - Projectile.png",
      bulletFrames: { max: 5 },
      bulletProps: {
        x: 6,
        y: 34,
        translate: 32,
      },
      size: {
        dw: 40,
        dh: 120,
        dy: 80,
      },
      weaponProps: {
        size: 40,
        translate: -23,
      },
      areaDamage: true,
      levelupcost: 20000000 * 100,
      weaponRotate: false,
    },
    {
      rate: 15,
      range: 220,
      damage: 50000,
      src: "./assets/towers/Tower 02.png",
      frames: { max: 3, current: 2 },
      weaponSrc: "./assets/weapons/Tower 02 - Level 03 - Weapon.png",
      weaponFrames: { max: 39 },
      bulletSrc: "./assets/bullets/Tower 02 - Level 01 - Projectile.png",
      bulletFrames: { max: 5 },
      bulletProps: {
        x: 6,
        y: 34,
        translate: 32,
      },
      size: {
        dw: 40,
        dh: 120,
        dy: 80,
      },
      weaponProps: {
        size: 40,
        translate: -23,
      },
      areaDamage: true,
      levelupcost: " max",
      weaponRotate: false,
    },
  ],
  tower03: [
    {
      rate: 40,
      range: 120,
      damage: 100000,
      src: "./assets/towers/Tower 03.png",
      frames: { max: 3, current: 0 },
      weaponSrc: "./assets/weapons/Tower 03 - Level 01 - Weapon.png",
      weaponFrames: { max: 8 },
      bulletSrc: "./assets/bullets/Tower 03 - Level 01 - Projectile.png",
      bulletFrames: { max: 6 },
      bulletProps: {
        x: 7,
        y: 7,
        translate: 23,
      },
      size: {
        dw: 40,
        dh: 80,
        dy: 40,
      },
      weaponProps: {
        size: 50,
        translate: -2,
      },
      areaDamage: false,
      levelupcost: 500000,
      weaponRotate: true,
    },
    {
      rate: 36,
      range: 130,
      damage: 100000 * 1.45,
      src: "./assets/towers/Tower 03.png",
      frames: { max: 3, current: 1 },
      weaponSrc: "./assets/weapons/Tower 03 - Level 02 - Weapon.png",
      weaponFrames: { max: 8 },
      bulletSrc: "./assets/bullets/Tower 03 - Level 02 - Projectile.png",
      bulletFrames: { max: 6 },
      bulletProps: {
        x: 7,
        y: 7,
        translate: 25,
      },
      size: {
        dw: 40,
        dh: 80,
        dy: 40,
      },
      weaponProps: {
        size: 50,
        translate: -7,
      },
      areaDamage: false,
      levelupcost: 500000 * 1.5,
      weaponRotate: true,
    },
    {
      rate: 32,
      range: 140,
      damage: 100000 * 2.1,
      src: "./assets/towers/Tower 03.png",
      frames: { max: 3, current: 2 },
      weaponSrc: "./assets/weapons/Tower 03 - Level 03 - Weapon.png",
      weaponFrames: { max: 8 },
      bulletSrc: "./assets/bullets/Tower 03 - Level 03 - Projectile.png",
      bulletFrames: { max: 6 },
      bulletProps: {
        x: 7,
        y: 7,
        translate: 27,
      },
      size: {
        dw: 40,
        dh: 80,
        dy: 40,
      },
      weaponProps: {
        size: 50,
        translate: -13,
      },
      areaDamage: false,
      levelupcost: 500000 * 2.25,
      weaponRotate: true,
    },
    {
      rate: 28,
      range: 150,
      damage: 100000 * 3.04,
      src: "./assets/towers/Tower 04.png",
      frames: { max: 3, current: 0 },
      weaponSrc: "./assets/weapons/Tower 04 - Level 01 - Weapon.png",
      weaponFrames: { max: 17 },
      bulletSrc: "./assets/bullets/Tower 04 - Level 01 - Projectile.png",
      bulletFrames: { max: 6 },
      bulletProps: {
        x: 9,
        y: 9,
        translate: 23,
      },
      size: {
        dw: 40,
        dh: 80,
        dy: 40,
      },
      weaponProps: {
        size: 50,
        translate: -7,
      },
      areaDamage: false,
      levelupcost: 500000 * 3.375,
      weaponRotate: true,
    },
    {
      rate: 24,
      range: 160,
      damage: 100000 * 4.42,
      src: "./assets/towers/Tower 04.png",
      frames: { max: 3, current: 1 },
      weaponSrc: "./assets/weapons/Tower 04 - Level 02 - Weapon.png",
      weaponFrames: { max: 17 },
      bulletSrc: "./assets/bullets/Tower 04 - Level 02 - Projectile.png",
      bulletFrames: { max: 6 },
      bulletProps: {
        x: 10,
        y: 10,
        translate: 26,
      },
      size: {
        dw: 40,
        dh: 80,
        dy: 40,
      },
      weaponProps: {
        size: 50,
        translate: -12,
      },
      areaDamage: false,
      levelupcost: 500000 * 5.06,
      weaponRotate: true,
    },
    {
      rate: 20,
      range: 170,
      damage: 100000 * 6.4,
      src: "./assets/towers/Tower 04.png",
      frames: { max: 3, current: 2 },
      weaponSrc: "./assets/weapons/Tower 04 - Level 03 - Weapon.png",
      weaponFrames: { max: 17 },
      bulletSrc: "./assets/bullets/Tower 04 - Level 03 - Projectile.png",
      bulletFrames: { max: 8 },
      bulletProps: {
        x: 8,
        y: 8,
        translate: 29,
      },
      size: {
        dw: 40,
        dh: 80,
        dy: 40,
      },
      weaponProps: {
        size: 50,
        translate: -17,
      },
      areaDamage: false,
      levelupcost: " max",
      weaponRotate: true,
    },
  ],
  tower04: [
    {
      rate: 40,
      range: 120,
      damage: 1000000,
      src: "./assets/towers/Tower 05.png",
      frames: { max: 3, current: 0 },
      weaponSrc: "./assets/weapons/Tower 05 - Level 01 - Weapon.png",
      weaponFrames: { max: 37 },
      bulletSrc: "./assets/bullets/Tower 05 - Level 01 - Projectile.png",
      bulletFrames: { max: 12 },
      bulletProps: {
        x: 19,
        y: 19,
        translate: 23,
      },
      size: {
        dw: 40,
        dh: 80,
        dy: 40,
      },
      weaponProps: {
        size: 80,
        translate: -12,
      },
      areaDamage: false,
      levelupcost: 3000000,
      weaponRotate: false,
    },
    {
      rate: 36,
      range: 130,
      damage: 1000000 * 1.3,
      src: "./assets/towers/Tower 05.png",
      frames: { max: 3, current: 1 },
      weaponSrc: "./assets/weapons/Tower 05 - Level 02 - Weapon.png",
      weaponFrames: { max: 37 },
      bulletSrc: "./assets/bullets/Tower 05 - Level 02 - Projectile.png",
      bulletFrames: { max: 12 },
      bulletProps: {
        x: 38,
        y: 38,
        translate: 26,
      },
      size: {
        dw: 40,
        dh: 80,
        dy: 40,
      },
      weaponProps: {
        size: 80,
        translate: -18,
      },
      areaDamage: false,
      levelupcost: 3000000 * 1.45,
      weaponRotate: false,
    },
    {
      rate: 32,
      range: 140,
      damage: 1000000 * 1.69,
      src: "./assets/towers/Tower 05.png",
      frames: { max: 3, current: 2 },
      weaponSrc: "./assets/weapons/Tower 05 - Level 03 - Weapon.png",
      weaponFrames: { max: 37 },
      bulletSrc: "./assets/bullets/Tower 05 - Level 03 - Projectile.png",
      bulletFrames: { max: 12 },
      bulletProps: {
        x: 44,
        y: 44,
        translate: 30,
      },
      size: {
        dw: 40,
        dh: 80,
        dy: 40,
      },
      weaponProps: {
        size: 80,
        translate: -24,
      },
      areaDamage: false,
      levelupcost: 3000000 * 2.1,
      weaponRotate: false,
    },
    {
      rate: 28,
      range: 150,
      damage: 1000000 * 2.19,
      src: "./assets/towers/Tower 07.png",
      frames: { max: 3, current: 0 },
      weaponSrc: "./assets/weapons/Tower 05 - Level 01 - Weapon.png",
      weaponFrames: { max: 37 },
      bulletSrc: "./assets/bullets/Tower 05 - Level 01 - Projectile.png",
      bulletFrames: { max: 12 },
      bulletProps: {
        x: 19,
        y: 19,
        translate: 23,
      },
      size: {
        dw: 40,
        dh: 80,
        dy: 40,
      },
      weaponProps: {
        size: 80,
        translate: -13,
      },
      areaDamage: false,
      levelupcost: 3000000 * 3.04,
      weaponRotate: false,
    },
    {
      rate: 24,
      range: 160,
      damage: 1000000 * 2.85,
      src: "./assets/towers/Tower 07.png",
      frames: { max: 3, current: 1 },
      weaponSrc: "./assets/weapons/Tower 05 - Level 02 - Weapon.png",
      weaponFrames: { max: 37 },
      bulletSrc: "./assets/bullets/Tower 05 - Level 02 - Projectile.png",
      bulletFrames: { max: 12 },
      bulletProps: {
        x: 38,
        y: 38,
        translate: 26,
      },
      size: {
        dw: 40,
        dh: 80,
        dy: 40,
      },
      weaponProps: {
        size: 80,
        translate: -18,
      },
      areaDamage: false,
      levelupcost: 3000000 * 4.42,
      weaponRotate: false,
    },
    {
      rate: 20,
      range: 170,
      damage: 1000000 * 3.71,
      src: "./assets/towers/Tower 07.png",
      frames: { max: 3, current: 2 },
      weaponSrc: "./assets/weapons/Tower 05 - Level 03 - Weapon.png",
      weaponFrames: { max: 37 },
      bulletSrc: "./assets/bullets/Tower 05 - Level 03 - Projectile.png",
      bulletFrames: { max: 12 },
      bulletProps: {
        x: 44,
        y: 44,
        translate: 30,
      },
      size: {
        dw: 40,
        dh: 80,
        dy: 40,
      },
      weaponProps: {
        size: 80,
        translate: -24,
      },
      areaDamage: false,
      levelupcost: " max",
      weaponRotate: false,
    },
  ],
  tower05: [
    {
      rate: 25,
      range: 150,
      damage: 10000000,
      src: "./assets/towers/Tower 08.png",
      frames: { max: 3, current: 0 },
      weaponSrc: "./assets/weapons/Tower 08 - Level 01 - Weapon.png",
      weaponFrames: { max: 10 },
      bulletSrc: "./assets/bullets/Tower 08 - Level 03 - Projectile.png",
      bulletFrames: { max: 17 },
      bulletProps: {
        x: 40,
        y: 40,
        translate: 25,
      },
      size: {
        dw: 40,
        dh: 120,
        dy: 80,
      },
      weaponProps: {
        size: 40,
        translate: -15,
      },
      areaDamage: false,
      levelupcost: 20000000,
      weaponRotate: false,
    },
    {
      rate: 22,
      range: 160,
      damage: 10000000 * 1.2,
      src: "./assets/towers/Tower 08.png",
      frames: { max: 3, current: 0 },
      weaponSrc: "./assets/weapons/Tower 08 - Level 01 - Weapon.png",
      weaponFrames: { max: 10 },
      bulletSrc: "./assets/bullets/Tower 08 - Level 03 - Projectile.png",
      bulletFrames: { max: 17 },
      bulletProps: {
        x: 40,
        y: 40,
        translate: 25,
      },
      size: {
        dw: 40,
        dh: 120,
        dy: 80,
      },
      weaponProps: {
        size: 40,
        translate: -15,
      },
      areaDamage: false,
      levelupcost: 20000000 * 2,
      weaponRotate: false,
    },
    {
      rate: 19,
      range: 170,
      damage: 10000000 * 1.44,
      src: "./assets/towers/Tower 08.png",
      frames: { max: 3, current: 1 },
      weaponSrc: "./assets/weapons/Tower 08 - Level 02 - Weapon.png",
      weaponFrames: { max: 10 },
      bulletSrc: "./assets/bullets/Tower 08 - Level 03 - Projectile.png",
      bulletFrames: { max: 17 },
      bulletProps: {
        x: 40,
        y: 40,
        translate: 29,
      },
      size: {
        dw: 40,
        dh: 120,
        dy: 80,
      },
      weaponProps: {
        size: 40,
        translate: -21,
      },
      areaDamage: false,
      levelupcost: 20000000 * 4,
      weaponRotate: false,
    },
    {
      rate: 16,
      range: 180,
      damage: 10000000 * 1.78,
      src: "./assets/towers/Tower 08.png",
      frames: { max: 3, current: 1 },
      weaponSrc: "./assets/weapons/Tower 08 - Level 02 - Weapon.png",
      weaponFrames: { max: 10 },
      bulletSrc: "./assets/bullets/Tower 08 - Level 03 - Projectile.png",
      bulletFrames: { max: 17 },
      bulletProps: {
        x: 40,
        y: 40,
        translate: 29,
      },
      size: {
        dw: 40,
        dh: 120,
        dy: 80,
      },
      weaponProps: {
        size: 40,
        translate: -21,
      },
      areaDamage: false,
      levelupcost: 20000000 * 8,
      weaponRotate: false,
    },
    {
      rate: 13,
      range: 190,
      damage: 10000000 * 2.07,
      src: "./assets/towers/Tower 08.png",
      frames: { max: 3, current: 2 },
      weaponSrc: "./assets/weapons/Tower 08 - Level 02 - Weapon.png",
      weaponFrames: { max: 10 },
      bulletSrc: "./assets/bullets/Tower 08 - Level 03 - Projectile.png",
      bulletFrames: { max: 17 },
      bulletProps: {
        x: 40,
        y: 40,
        translate: 29,
      },
      size: {
        dw: 40,
        dh: 120,
        dy: 80,
      },
      weaponProps: {
        size: 40,
        translate: -27,
      },
      areaDamage: false,
      levelupcost: 20000000 * 20,
      weaponRotate: false,
    },
    {
      rate: 11,
      range: 200,
      damage: 10000000 * 2.6,
      src: "./assets/towers/Tower 08.png",
      frames: { max: 3, current: 2 },
      weaponSrc: "./assets/weapons/Tower 08 - Level 03 - Weapon.png",
      weaponFrames: { max: 10 },
      bulletSrc: "./assets/bullets/Tower 08 - Level 03 - Projectile.png",
      bulletFrames: { max: 17 },
      bulletProps: {
        x: 40,
        y: 40,
        translate: 36,
      },
      size: {
        dw: 40,
        dh: 120,
        dy: 80,
      },
      weaponProps: {
        size: 50,
        translate: -27,
      },
      areaDamage: false,
      levelupcost: " max",
      weaponRotate: false,
    },
  ],
};

const States = {
  waypoints: adjustWaypoints(),
  placementTilesData: [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1191, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1191, 0, 0, 0, 1191, 0, 0,
    1191, 0, 0, 1191, 0, 0, 1191, 0, 0, 0, 0, 0, 0, 1191, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1191, 0, 0, 0, 0, 0, 0, 0, 0,
    1191, 0, 0, 1191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1191, 0, 1191, 0, 1191, 0, 1191, 0, 1191,
    0, 0, 0, 1191, 0, 0, 0, 0, 0, 0, 0, 0, 1191, 0, 0, 1191, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1191, 0, 0, 0, 0, 0, 0, 0, 0, 1191, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1191, 0, 0, 0,
    0, 0, 0, 0, 1191, 0, 0, 0, 0, 0, 1191, 0, 0, 1191, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 1191, 0, 0, 0, 1191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  ],

  amountOfBuildings: 5,
};
